/**
 * @file    errmsg.h
 * @brief   Error messages for SIMPL-2018.
 * @author  W. H. K. Bester (whkbester@cs.sun.ac.za)
 * @date    2018-07-09
 */

#ifndef ERRMSG_H
#define ERRMSG_H

typedef enum {

	ERR_ARGUMENT_LIST_OR_VARIABLE_ASSIGNMENT_EXPECTED,
	ERR_ARRAY_ALLOCATION_OR_EXPRESSION_EXPECTED,
	ERR_EXIT_EXPRESSION_NOT_ALLOWED_FOR_PROCEDURE,
	ERR_EXPECT,
	ERR_EXPRESSION_OR_STRING_EXPECTED,
	ERR_FACTOR_EXPECTED,
	ERR_ILLEGAL_ARRAY_OPERATION,
	ERR_MISSING_EXIT_EXPRESSION_FOR_FUNCTION,
	ERR_MISSING_FUNCTION_ARGUMENT_LIST,
	ERR_MULTIPLE_DEFINITION,
	ERR_NOT_A_FUNCTION,
	ERR_NOT_A_PROCEDURE,
	ERR_NOT_A_VARIABLE,
	ERR_NOT_AN_ARRAY,
	ERR_SCALAR_VARIABLE_EXPECTED,
	ERR_STATEMENT_EXPECTED,
	ERR_TAKES_NO_ARGUMENTS,
	ERR_TOO_FEW_ARGUMENTS,
	ERR_TOO_MANY_ARGUMENTS,
	ERR_TYPE_EXPECTED,
	ERR_UNKNOWN_IDENTIFIER,
	ERR_UNREACHABLE

} Error;

#endif /* ERRMSG_H */
